sous-chefs/nrpe

- .kitchen.yml
- Berksfile
- Vagrantfile
- attributes/default.rb
- providers/check.rb
- test/fixtures/cookbooks/chef_nrpe_test/metadata.rb
- test/fixtures/cookbooks/chef_nrpe_test/recipes/default.rb
This adds a few features to the nrpe recipe to support CentOS 7.
1. Add the CentOS 7 bits to Vagrantfile and kitchen.yml
2. Add test fixture to verify lwrp nrpe_check is tested
3. Attribute'ize the reload of a nrpe_check to restart on CentOS 7 vs other OSs
> Support CentOS 7

- .travis.yml
- Gemfile
- attributes/default.rb
- recipes/default.rb
We use chef searches to add nodes in our monitoring system. But in this case we must configure checks twice: on the node and on the monitoring system, because we can't get list of configured checks from the node.  We would like configure checks in one place, on the node.
The essence of this PR is to add the node attribute which we can use to get all checks on the node and configure same checks on monitoring system automatically.
> The attribute ['nrpe']['checks'], which stores all configured checks.

- README.md
- attributes/default.rb
- recipes/_package_install.rb
Hi,
Some organisations will have an local copy of the EPEL repo or may use a custom repo with only packages they require. In this case we can provide the option below to skip the `include_recipe 'yum-epel'` based on user preference. Default behaviour remains the same.
Regards,
Peter
> Make yum-epel recipe optional

- recipes/default.rb
For some reason beyond my time-limited understanding the NRPE service is intermittently delayed during startup on Centos 7. The converge eventually times out for the service resource. Subsequent runs usually prove successful.
> Resolve NRPE svc startup delay error occuring under systemd on centos 7

- CHANGELOG.md
- attributes/default.rb
- metadata.rb
- recipes/_package_install.rb
['nrpe']['packages'] is now a Hash. Each package has a version attribute
which is nil by default
default['nrpe']['packages'] = {
'nagios-nrpe-server'      => {'version' => nil},
'nagios-plugins'          => {'version' => nil},
'nagios-plugins-basic'    => {'version' => nil},
'nagios-plugins-standard' => {'version' => nil}
}
In your wrapper / role you can define version for any / all of the
packages as example below:
default!['nrpe']['packages']['nrpe']['version'] = "2.15-2.el#{node['platform_version'][0]}"
Default behavious will be the same as before. If version is nil, latest
version found in repositories will be installed otherwise requested version will be installed.
> Ability to install desired version of NRPE packages instead of latest one

- attributes/default.rb
Need logic so RHEL7 uses "nrpe" as user/group by default instead of "nagios". Default "nagios" user/group doesn't seem to work right with the nrpe_check LWRP and causes permission errors when trying to run these checks.
> Add default rhel7 user/group logic

- providers/check.rb
- recipes/_source_nrpe.rb
- recipes/default.rb
...so that nagios user can not modify them
now nagios user can only read the files, but not modify. also prevent others to read the files.
especially important is nagios owned `/etc/init.d/nrpe` init-script: if nagios user can modify it, it has to wait for sysadmin (or machine reboot) to execute the script to gain root privileges to the system.
`node['nrpe']['user']` is still used, defining what uid will be used to startup nrpe daemon
> increase security by owning files by root

- .rubocop.yml
- README.md
- providers/check.rb
- resources/check.rb
this adds support for template in LWRP, similar to [sudo](https://github.com/chef-cookbooks/sudo) cookbook:
```ruby
nrpe_check 'nf_conntrack_max' do
template 'nf_conntrack_max.cfg.erb'
action :add
end
```
this can be used if one wishes to have complex definition or just wishing to have multiple commands defined in same nrpe config file fragment.
> add template support

- recipes/configure.rb
- templates/default/nrpe.service.erb
This fixes centos7 usage with non-default nrpe user attributes.
> ensure that systemd unit file matches the nrpe user attribute

- templates/default/nagios-nrpe-server.erb
I was having this problem on my Ubuntu 14.10 install when the cookbook tries to add nagios-nrpe-server to the default runlevels.
```
insserv: warning: script 'nagios-nrpe-server' missing LSB tags and overrides
insserv: There is a loop between service monit and nagios-nrpe-server if stopped
insserv:  loop involving service nagios-nrpe-server at depth 2
insserv:  loop involving service monit at depth 1
insserv: Stopping nagios-nrpe-server depends on monit and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
```
Adding the header fixed the problem.
> add LSB header to init script

- providers/check.rb
it looks better this way when looking the files from terminal using cat
some parsers even may break without newlines (shell scripts for example!)
> always include newline in resource files

- metadata.rb
- providers/check.rb
- recipes/_source_nrpe.rb
- recipes/configure.rb
On systems that have systemd, the rate limiting will kick in and mark the nrpe service as failed if a lot of checks are changed. This causes the chef-run to fail.
Also, it makes sense to only restart NRPE once at the end of the run when all the files are in place.
> Only restart NRPE at the end of the chef-run

- metadata.rb
Update metadata info to reflect cookbook is now maintained by Sous Chefs.
> Update metadata maintainer and repo urls

- templates/default/nrpe.cfg.erb
Systemd doesn't require a pid-file so it might be useful to skip writing this attribute.
This change makes it the attribute fully configurable.
This change makes the pid_file attribute optional.
It wasn't possible to run nrpe without a pid_file. 
NRPE fails when the pid_file option is configured but empty.
> Don't write an empty pid_file attribute

- README.md
- recipes/configure.rb
- spec/default_spec.rb
Allows the IPv6 localhost ::1 by default
[List any existing issues this PR resolves]
> allow IPv6 localhost ::1

- Dangerfile
Description
Describe what this change achieves
use `failure` directive instead of `fail`
List any existing issues this PR resolves
closes #106
> update Dangerfile to use `failure` instead of `fail`

- CHANGELOG.md
- attributes/default.rb
- recipes/_source_nrpe.rb
- templates/default/nrpe-tmpfiles.d.erb
Updated nrpe to work with cookbook changes before pid changes. 
Updated systemd tmpfile config file to be managed by chef so pid failures wont happen on boot.
N/A (I can make an issue if one is needed)
> Systemd systems fail to start nrpe on boot. Updated nrpe to get it working via cookbook.

- CHANGELOG.md
- recipes/_source_nrpe.rb
- spec/ubuntu_source_spec.rb
We discovered a few nodes in our stack that were centos 6 had the nrpe installed in /usr/bin/nrpe and was the one getting picked up. The cookbook would compile the newer version and put it in /usr/sbin/nrpe. That new one was ignored and would cause the cookbook every run to compile nrpe.
Should I create an issue?
> Add bin dir path to version check

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- kitchen.dokken.yml
- kitchen.yml
- metadata.rb
- resources/check.rb
- test/integration/check/inspec/check_spec.rb
- test/integration/package/inspec/package_spec.rb
- test/integration/source/inspec/source_spec.rb
Signed-off-by: Robert Detjens <detjensrobert@osuosl.org>
Enable `unified_mode` for Chef 17 compatibility.
Major bump as this bumps the required Chef version to 15.3.
> Enable unified_mode for Chef 17 compatibility

- CHANGELOG.md
- attributes/default.rb
- kitchen.dokken.yml
- kitchen.yml
- recipes/_source_nrpe.rb
- recipes/configure.rb
- spec/ubuntu_source_spec.rb
Hey!
I ran Cookstyle 7.25.6 against this repo and here are the results.
This repo was selected due to the topics of chef-cookbook
- 106:6 refactor: `Chef/Modernize/UseChefLanguageSystemdHelper` - Chef Infra Client 15.5 and later include a `systemd?` helper for checking if a Linux system uses systemd. (https://docs.chef.io/workstation/cookstyle/chef_modernize_usecheflanguagesystemdhelper)
- 30:4 refactor: `Chef/Modernize/UseChefLanguageSystemdHelper` - Chef Infra Client 15.5 and later include a `systemd?` helper for checking if a Linux system uses systemd. (https://docs.chef.io/workstation/cookstyle/chef_modernize_usecheflanguagesystemdhelper)
- 85:13 refactor: `Chef/Modernize/UseChefLanguageSystemdHelper` - Chef Infra Client 15.5 and later include a `systemd?` helper for checking if a …
> Automated PR: Cookstyle Changes
